version: "3.8"

services:
  cfnat-aio:
    image: ghcr.io/mqiancheng/cfnat-aio:latest
    container_name: cfnat-aio
    restart: unless-stopped
    ports:
      - "192.168.7.4:1234:1234"   # WebUI
      - "192.168.7.4:1001:1001"   # HKG proxy
      - "192.168.7.4:1002:1002"   # LAX proxy
      - "192.168.7.4:1003:1003"   # JP proxy
      # 后续新增地区只需在 WebUI 操作，端口会按需添加
    user: "1000:1000"
    volumes:
      - /vol1/1000/docker/cfnat-aio:/data
    environment:
      - TZ=Asia/Shanghai
    networks:
      bt_direct_net:
        ipv4_address: 192.168.7.4

networks:
  bt_direct_net:
    external: true
    name: bt_direct_net
